name: CI

on:
  push:
    branches: [ "develop", "main","mauricioleaño_p2_dev","mauricioleaño_p2_base" ]
  pull_request:
    branches: [ "develop", "main" ,"mauricioleaño_p2_dev","mauricioleaño_p2_base" ]

  workflow_dispatch:

env: 
  SEM_VERSION: ${{github.run_id}}
  IMAGE_NAME:  "restapp"
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  ## 🔧 1. 
  Static-codecheck:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: test
        run: python -m pytest test/unit -v

  ## 🔧 2. 
  Build:
    runs-on: self-hosted
    needs: Static-codecheck

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: build
        run: docker build -t $IMAGE_NAME:1.0.$SEM_VERSION .

      - name: tag
        run: docker tag $IMAGE_NAME:1.0.$SEM_VERSION mauriciolsalles/$IMAGE_NAME:1.0.$SEM_VERSION

      - name: push
        run: docker push mauriciolsalles/$IMAGE_NAME:1.0.$SEM_VERSION 
#  ## 🚀 3. 
  deploy-dev:
    runs-on: self-hosted
    needs: Build
    environment:
      name: Develop
      url: http://localhost:5000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: build compose
        run: docker compose -f 'compose.yaml' up -d $IMAGE_NAME --force-recreate

      - name: run integration test
        run: docker exec $IMAGE_NAME sh -c "python -m pytest test/integration -v"

      - name: cleanup
        run: docker compose down
#
#  ## 🚀 4. 
  deploy-prod:
    runs-on: self-hosted
    needs: deploy-dev
    if: github.ref == 'refs/heads/mauricioleaño_p2_base' 
    environment:
      name: Production
      url: http://localhost:5000 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: build compose
        run: docker compose -f 'compose.yaml' up -d  $IMAGE_NAME --force-recreate

      - name: run integration test
        run: docker exec $IMAGE_NAME sh -c "python -m pytest test/integration -v"

      - name: run integration test with newman
        run:  docker run --rm --network host  -v "./tests:/etc/newman"   postman/newman run collection.json 

      - name: cleanup
        run: docker compose down